export interface Currency {
  code: string;
  name?: string;
  symbol?: string;
}

export interface Country {
  id?: number; // Auto-generated by DB
  name: string;
  capital: string | null;
  region: string | null;
  population: number; // Required field as per task requirements
  currency_code: string | null;
  exchange_rate: number | null;
  estimated_gdp: number | null;
  flag_url: string | null;
  last_refreshed_at: Date;
}
